####
# This Dockerfile is used in order to build a container that runs the Quarkus application in native (no JVM) mode
#
###
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.1.0 
WORKDIR /work/
RUN chown 1001:1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:1001 /work
COPY --chown=1001:1001 target/*-runner /work/application

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]